del .\tage\*.class
del .\tage\ai\behaviortrees\*.class
del .\tage\audio\*.class
del .\tage\audio\joal\*.class
del .\tage\input\*.class
del .\tage\input\action\*.class
del .\tage\networking\*.class
del .\tage\networking\client\*.class
del .\tage\networking\server\*.class
del .\tage\nodeControllers\*.class
del .\tage\objectRenderers\*.class
del .\tage\physics\*.class
del .\tage\rml\*.class
del .\tage\shapes\*.class
